server:
  port: 8083

spring:
  datasource:
    hikari:
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 30000
      jdbc-url: jdbc:h2:~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 50
    url: ${spring.datasource.hikari.jdbc-url}
    driver-class-name: ${spring.datasource.hikari.driver-class-name}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      org.hibernate.envers.audit_table_suffix: _HIS
      org.hibernate.envers.modified_flag_suffix: _CHANGED
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 10
#      hibernate.generate_statistics: true
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
debug: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG